install.packages("dplyr",
                 "ggplot2",
                 "ggthemes",
                 "extrafont",
                 "tidyr",
                 "patchwork",
                 "scales",
                 "plotly",
                 "shinydashboard")
